// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthStatus() {
  return window['go']['app']['App']['AuthStatus']();
}

export function CancelAllTasks() {
  return window['go']['app']['App']['CancelAllTasks']();
}

export function CancelTask(arg1) {
  return window['go']['app']['App']['CancelTask'](arg1);
}

export function ClearCompletedTasks() {
  return window['go']['app']['App']['ClearCompletedTasks']();
}

export function ConfigDir() {
  return window['go']['app']['App']['ConfigDir']();
}

export function Copy(arg1, arg2) {
  return window['go']['app']['App']['Copy'](arg1, arg2);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['app']['App']['CreateFolder'](arg1, arg2);
}

export function CreateShareLink(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateShareLink'](arg1, arg2, arg3);
}

export function Delete(arg1) {
  return window['go']['app']['App']['Delete'](arg1);
}

export function DeleteShare(arg1) {
  return window['go']['app']['App']['DeleteShare'](arg1);
}

export function EnqueueDownloads(arg1) {
  return window['go']['app']['App']['EnqueueDownloads'](arg1);
}

export function EnqueueUploads(arg1, arg2) {
  return window['go']['app']['App']['EnqueueUploads'](arg1, arg2);
}

export function EnsureDownloadDir(arg1) {
  return window['go']['app']['App']['EnsureDownloadDir'](arg1);
}

export function GetProfile() {
  return window['go']['app']['App']['GetProfile']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function ListDir(arg1) {
  return window['go']['app']['App']['ListDir'](arg1);
}

export function ListMyShares(arg1, arg2) {
  return window['go']['app']['App']['ListMyShares'](arg1, arg2);
}

export function ListTasks() {
  return window['go']['app']['App']['ListTasks']();
}

export function Login(arg1) {
  return window['go']['app']['App']['Login'](arg1);
}

export function LoginFromEnv() {
  return window['go']['app']['App']['LoginFromEnv']();
}

export function Logout() {
  return window['go']['app']['App']['Logout']();
}

export function Move(arg1, arg2) {
  return window['go']['app']['App']['Move'](arg1, arg2);
}

export function ParseShare(arg1) {
  return window['go']['app']['App']['ParseShare'](arg1);
}

export function PauseAllTasks() {
  return window['go']['app']['App']['PauseAllTasks']();
}

export function PauseTask(arg1) {
  return window['go']['app']['App']['PauseTask'](arg1);
}

export function PickDownloadDir() {
  return window['go']['app']['App']['PickDownloadDir']();
}

export function PickUploadFiles() {
  return window['go']['app']['App']['PickUploadFiles']();
}

export function Rename(arg1, arg2) {
  return window['go']['app']['App']['Rename'](arg1, arg2);
}

export function ResolveFid(arg1) {
  return window['go']['app']['App']['ResolveFid'](arg1);
}

export function ResumeAllTasks() {
  return window['go']['app']['App']['ResumeAllTasks']();
}

export function ResumeTask(arg1) {
  return window['go']['app']['App']['ResumeTask'](arg1);
}

export function RetryTask(arg1) {
  return window['go']['app']['App']['RetryTask'](arg1);
}

export function RevealLocal(arg1) {
  return window['go']['app']['App']['RevealLocal'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SaveShare(arg1) {
  return window['go']['app']['App']['SaveShare'](arg1);
}

export function Search(arg1, arg2, arg3) {
  return window['go']['app']['App']['Search'](arg1, arg2, arg3);
}
