// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {config} from '../models';

export function AuthStatus():Promise<app.AuthState>;

export function CancelAllTasks():Promise<number>;

export function CancelTask(arg1:string):Promise<boolean>;

export function ClearCompletedTasks():Promise<number>;

export function ConfigDir():Promise<string>;

export function Copy(arg1:string,arg2:string):Promise<boolean>;

export function CreateFolder(arg1:string,arg2:string):Promise<app.FileItem>;

export function CreateShareLink(arg1:string,arg2:number,arg3:boolean):Promise<app.ShareLink>;

export function Delete(arg1:Array<string>):Promise<number>;

export function DeleteShare(arg1:Array<string>):Promise<boolean>;

export function EnqueueDownloads(arg1:Array<app.DownloadItem>):Promise<Array<app.TaskDTO>>;

export function EnqueueUploads(arg1:Array<string>,arg2:string):Promise<Array<app.TaskDTO>>;

export function EnsureDownloadDir(arg1:string):Promise<string>;

export function GetProfile():Promise<app.Profile>;

export function GetSettings():Promise<config.Settings>;

export function ListDir(arg1:string):Promise<app.DirListing>;

export function ListMyShares(arg1:number,arg2:number):Promise<Array<app.MyShareItem>>;

export function ListTasks():Promise<Array<app.TaskDTO>>;

export function Login(arg1:string):Promise<app.AuthState>;

export function LoginFromEnv():Promise<app.AuthState>;

export function Logout():Promise<boolean>;

export function Move(arg1:string,arg2:string):Promise<boolean>;

export function ParseShare(arg1:string):Promise<app.SharePreview>;

export function PauseAllTasks():Promise<number>;

export function PauseTask(arg1:string):Promise<boolean>;

export function PickDownloadDir():Promise<string>;

export function PickUploadFiles():Promise<Array<string>>;

export function Rename(arg1:string,arg2:string):Promise<boolean>;

export function ResolveFid(arg1:string):Promise<string>;

export function ResumeAllTasks():Promise<number>;

export function ResumeTask(arg1:string):Promise<boolean>;

export function RetryTask(arg1:string):Promise<boolean>;

export function RevealLocal(arg1:string):Promise<string>;

export function SaveSettings(arg1:config.Settings):Promise<config.Settings>;

export function SaveShare(arg1:app.SaveShareRequest):Promise<app.SaveShareResult>;

export function Search(arg1:string,arg2:string,arg3:boolean):Promise<app.DirListing>;
